EMBED_COLOUR = 0xFF0017

EMBED_AUTHOR = {
    "name": "BNO News",
    "url": "https://bnonews.com/index.php/2020/02/the-latest-coronavirus-cases/",
    "icon_url": "https://i.imgur.com/haxMkD5.png",
}

EMBED_FIELDS = {
    "cases": {"name": "**__Cases__**", "inline": True},
    "serious": {"name": "**__Serious__**", "inline": True},
    "critical": {"name": "**__Critical__**", "inline": True},
    "deaths": {"name": "**__Deaths__**", "inline": True},
    "recovered": {"name": "**__Recovered__**", "inline": False},
}

FLAG_THUMBNAIL_URL_MAPPER = {
    "Afghanistan": "https://i.imgur.com/irugyfa.png",
    "Albania": "https://i.imgur.com/Zq4wx27.png",
    "Algeria": "https://i.imgur.com/7XD0ijj.png",
    "American Samoa": "https://i.imgur.com/icrpqhI.png",
    "Andorra": "https://i.imgur.com/zBan22G.png",
    "Angola": "https://i.imgur.com/irugyfa.png",
    "Anguilla": "https://i.imgur.com/szEyeDt.png",
    "Antarctica": "https://i.imgur.com/u9RAJkf.png",
    "Antigua and Barbuda": "https://i.imgur.com/HZEOpDO.png",
    "Argentina": "https://i.imgur.com/2GEPHUS.png",
    "Armenia": "https://i.imgur.com/D9lGty9.png",
    "Aruba": "https://i.imgur.com/1k8LGjh.png",
    "Australia": "https://i.imgur.com/3s0X5CX.png",
    "Austria": "https://i.imgur.com/4Qirh5P.png",
    "Azerbaijan": "https://i.imgur.com/zOYSA9r.png",
    "Bahamas": "https://i.imgur.com/HRaZiYM.png",
    "Bahrain": "https://i.imgur.com/bQaYFJe.png",
    "Bangladesh": "https://i.imgur.com/6RYaT0u.png",
    "Barbados": "https://i.imgur.com/PbTVWRk.png",
    "Belarus": "https://i.imgur.com/jMW5p1g.png",
    "Belgium": "https://i.imgur.com/tt2OJ28.png",
    "Belize": "https://i.imgur.com/yRRxO6L.png",
    "Benin": "https://i.imgur.com/VcJWHWI.png",
    "Bermuda": "https://i.imgur.com/zy4Ld96.png",
    "Bhutan": "https://i.imgur.com/nnggWIa.png",
    "BIOT": "https://i.imgur.com/ggbiHgN.png",
    "Bolivia": "https://i.imgur.com/VBUec6s.png",
    "Bosnia": "https://i.imgur.com/0Bk0CbR.png",
    "Botswana": "https://i.imgur.com/AWbdc51.png",
    "Bouvet Island": "https://i.imgur.com/gIRS94L.png",
    "Brazil": "https://i.imgur.com/wdRH00C.png",
    "British Antarctic Territory": "https://i.imgur.com/GEg4qmg.png",
    "British Virgin Islands": "https://i.imgur.com/KahsK6P.png",
    "Brunei": "https://i.imgur.com/CwQT168.png",
    "Bulgaria": "https://i.imgur.com/eXxueRV.png",
    "Burkina Faso": "https://i.imgur.com/tMv5QDL.png",
    "Burma": "https://i.imgur.com/TgiaWtr.png",
    "Burundi": "https://i.imgur.com/XVOCkty.png",
    "Cambodia": "https://i.imgur.com/1Vam3mR.png",
    "Cameroon": "https://i.imgur.com/YiW082m.png",
    "Canada": "https://i.imgur.com/CAeMa0w.png",
    "Cape Verde": "https://i.imgur.com/pQNpcWP.png",
    "Cayman Islands": "https://i.imgur.com/tDcPNSE.png",
    "Central African Republic": "https://i.imgur.com/OKr1rI9.png",
    "Chad": "https://i.imgur.com/EIK4U3b.png",
    "Chile": "https://i.imgur.com/JNlJgDA.png",
    "China": "https://i.imgur.com/GoCvEKU.png",
    "Mainland China": "https://i.imgur.com/GoCvEKU.png",
    "Christmas Island": "https://i.imgur.com/yfEWbny.png",
    "Cocos Islands": "https://i.imgur.com/1k35ZAj.png",
    "Colombia": "https://i.imgur.com/vX7Bxv3.png",
    "Comoros": "https://i.imgur.com/TVcroA6.png",
    "Congo": "https://i.imgur.com/d0gmvhQ.png",
    "Congo Kinshasa": "https://i.imgur.com/fca07Hp.png",
    "Cook Islands": "https://i.imgur.com/EVJKkoZ.png",
    "Costa Rica": "https://i.imgur.com/A9kbaxs.png",
    "Croatia": "https://i.imgur.com/oZ7AaiH.png",
    "Cuba": "https://i.imgur.com/ioL36Os.png",
    "Cyprus": "https://i.imgur.com/SDWaELR.png",
    "Czech Republic": "https://i.imgur.com/QRHAaCH.png",
    "Denmark": "https://i.imgur.com/1k9ibDE.png",
    "Djibouti": "https://i.imgur.com/hOBjfQd.png",
    "Dominican Republic": "https://i.imgur.com/7g24OEZ.png",
    "Dominicana": "https://i.imgur.com/ZnD4E8S.png",
    "East Timor": "https://i.imgur.com/8p9nBhz.png",
    "Ecuador": "https://i.imgur.com/COnmZX5.png",
    "Egypt": "https://i.imgur.com/DRZsNG4.png",
    "El Salvador": "https://i.imgur.com/khrIsfB.png",
    "England": "https://i.imgur.com/RCruXRo.png",
    "Equatorial Guinea": "https://i.imgur.com/RPjVh2W.png",
    "Eritrea": "https://i.imgur.com/bamfhgn.png",
    "Estonia": "https://i.imgur.com/7j5ki7T.png",
    "Ethiopia": "https://i.imgur.com/WJppxEG.png",
    "Ex Yugoslavia": "https://i.imgur.com/JiMQGLt.png",
    "Falkland Islands": "https://i.imgur.com/ulfVJGM.png",
    "Faroe Islands": "https://i.imgur.com/GEjdcxP.png",
    "Fiji": "https://i.imgur.com/qpJX6WK.png",
    "Finland": "https://i.imgur.com/7kkRrA2.png",
    "France": "https://i.imgur.com/Z2a6n5C.png",
    "French Polynesia": "https://i.imgur.com/Xpb0Nyf.png",
    "French Southern Territories": "https://i.imgur.com/80E9Mza.png",
    "Gabon": "https://i.imgur.com/SMpgAZA.png",
    "Gambia": "https://i.imgur.com/2h3zGzY.png",
    "Georgia": "https://i.imgur.com/C7lsBqI.png",
    "Germany": "https://i.imgur.com/Ay0c03j.png",
    "Ghana": "https://i.imgur.com/lTL4TCm.png",
    "Gibraltar": "https://i.imgur.com/AvQ4kyh.png",
    "Greece": "https://i.imgur.com/83E8MG4.png",
    "Greenland": "https://i.imgur.com/lKDnnVU.png",
    "Grenada": "https://i.imgur.com/isHFHFe.png",
    "Guadeloupe": "https://i.imgur.com/hNNF5ij.png",
    "Guam": "https://i.imgur.com/FHREB0p.png",
    "Guatemala": "https://i.imgur.com/vuKtk0r.png",
    "Guernsey": "https://i.imgur.com/xgfozcK.png",
    "Guinea Bissau": "https://i.imgur.com/IV7cF26.png",
    "Guinea": "https://i.imgur.com/69fIc2C.png",
    "Guyana": "https://i.imgur.com/XWc3qqP.png",
    "Haiti": "https://i.imgur.com/bJYvEaF.png",
    "Holy See": "https://i.imgur.com/sfnWuQ7.png",
    "Honduras": "https://i.imgur.com/2SsE8kj.png",
    "Hong Kong": "https://i.imgur.com/WA3uZBu.png",
    "Hungary": "https://i.imgur.com/TXpzvIo.png",
    "Iceland": "https://i.imgur.com/jhWJVSR.png",
    "India": "https://i.imgur.com/kdoGv8n.png",
    "Indonesia": "https://i.imgur.com/JFj2P9s.png",
    "Iran": "https://i.imgur.com/xuMP0lI.png",
    "Iraq": "https://i.imgur.com/yeAwxxr.png",
    "Ireland": "https://i.imgur.com/OJGWloo.png",
    "Isle of Man": "https://i.imgur.com/towOxgD.png",
    "Israel": "https://i.imgur.com/EtnWFrW.png",
    "Italy": "https://i.imgur.com/rfwb0gY.png",
    "Ivory Coast": "https://i.imgur.com/quCv2e1.png",
    "Jamaica": "https://i.imgur.com/Vu9u6tK.png",
    "Jan Mayen": "https://i.imgur.com/Hnbcf8f.png",
    "Japan": "https://i.imgur.com/Oak9dor.png",
    "Jarvis Island": "https://i.imgur.com/v2BXZND.png",
    "Jersey": "https://i.imgur.com/wYeBUk5.png",
    "Jordan": "https://i.imgur.com/ElbaV7z.png",
    "Kazakhstan": "https://i.imgur.com/CzAM8m7.png",
    "Kenya": "https://i.imgur.com/ZepK6bP.png",
    "Kiribati": "https://i.imgur.com/uOHruF1.png",
    "South Korea": "https://i.imgur.com/tPhSriY.png",
    "Kuwait": "https://i.imgur.com/zJvDJXF.png",
    "Kyrgyzstan": "https://i.imgur.com/qZnAHzJ.png",
    "Laos": "https://i.imgur.com/OZWjkRI.png",
    "Latvia": "https://i.imgur.com/CPlOI66.png",
    "Lebanon": "https://i.imgur.com/k9jAJa2.png",
    "Lesotho": "https://i.imgur.com/kS73Tp4.png",
    "Liberia": "https://i.imgur.com/ujyoV5W.png",
    "Libya": "https://i.imgur.com/KGHEfo1.png",
    "Liechtenstein": "https://i.imgur.com/Ls7u88D.png",
    "Lithuania": "https://i.imgur.com/NIYcuMd.png",
    "Luxembourg": "https://i.imgur.com/128rfoL.png",
    "Macau": "https://i.imgur.com/1ikr0Ar.png",
    "Macedonia": "https://i.imgur.com/dRtljn0.png",
    "Madagascar": "https://i.imgur.com/mhGD3M3.png",
    "Malawi": "https://i.imgur.com/lozy7KX.png",
    "Malaysia": "https://i.imgur.com/gjXkrq2.png",
    "Maldives": "https://i.imgur.com/actYjVr.png",
    "Mali": "https://i.imgur.com/0Py5N5K.png",
    "Malta": "https://i.imgur.com/Ops0RSh.png",
    "Marshall Islands": "https://i.imgur.com/6HkEnDl.png",
    "Martinique": "https://i.imgur.com/p6ZY1QO.png",
    "Mauritania": "https://i.imgur.com/C7v3wln.png",
    "Mauritius": "https://i.imgur.com/PlicHyp.png",
    "Mayotte": "https://i.imgur.com/5rEwjbB.png",
    "Mexico": "https://i.imgur.com/xofYXiF.png",
    "Micronesia": "https://i.imgur.com/Nlch8dm.png",
    "Moldova": "https://i.imgur.com/lIxxsEg.png",
    "Monaco": "https://i.imgur.com/e5HuzZK.png",
    "Mongolia": "https://i.imgur.com/4xIt3Sp.png",
    "Montenegro": "https://i.imgur.com/SpILGuN.png",
    "Montserrat": "https://i.imgur.com/o6DvPT2.png",
    "Morocco": "https://i.imgur.com/ZhscZhd.png",
    "Mozambique": "https://i.imgur.com/gqN0W0b.png",
    "Myanmar": "https://i.imgur.com/idFBnwI.png",
    "Namibia": "https://i.imgur.com/948uJv6.png",
    "Nauru": "https://i.imgur.com/fuvkBW3.png",
    "Nepal": "https://i.imgur.com/wfHgx6C.png",
    "Netherlands Antilles": "https://i.imgur.com/jzgkMYO.png",
    "Netherlands": "https://i.imgur.com/ToXQumA.png",
    "New Caledonia": "https://i.imgur.com/Jsg3AIJ.png",
    "New Zealand": "https://i.imgur.com/ByoLTKO.png",
    "Nicaragua": "https://i.imgur.com/eSa68Cr.png",
    "Niger": "https://i.imgur.com/KUSjrwj.png",
    "Nigeria": "https://i.imgur.com/LdE8IO7.png",
    "Niue": "https://i.imgur.com/NsrmP4g.png",
    "Norfolk Island": "https://i.imgur.com/2GJWRAM.png",
    "North Korea": "https://i.imgur.com/qPLsh3L.png",
    "Northern Ireland": "https://i.imgur.com/euqQwvI.png",
    "Northern Mariana Islands": "https://i.imgur.com/F5oy6LW.png",
    "Norway": "https://i.imgur.com/94wEKxG.png",
    "Oman": "https://i.imgur.com/RApcpdq.png",
    "Pakistan": "https://i.imgur.com/FH55cKV.png",
    "Palau": "https://i.imgur.com/7Bk7F3w.png",
    "Palestinian Territory": "https://i.imgur.com/G0CWCRw.png",
    "Panama": "https://i.imgur.com/GDx7GMV.png",
    "Papua New Guinea": "https://i.imgur.com/aj1cm03.png",
    "Paraguay": "https://i.imgur.com/hBTSdW5.png",
    "Peru": "https://i.imgur.com/NnF3vjw.png",
    "Philippines": "https://i.imgur.com/msu0D2G.png",
    "Pitcairn": "https://i.imgur.com/NrrmvQl.png",
    "Poland": "https://i.imgur.com/gPsEx8r.png",
    "Portugal": "https://i.imgur.com/4wCFcbu.png",
    "Puerto Rico": "https://i.imgur.com/l6FdB42.png",
    "Qatar": "https://i.imgur.com/zhv3LQ2.png",
    "Reunion": "https://i.imgur.com/HJWa87K.png",
    "Romania": "https://i.imgur.com/ddlV8Xv.png",
    "Russia": "https://i.imgur.com/jfEq4Tl.png",
    "Rwanda": "https://i.imgur.com/X6c1J9t.png",
    "Saint Pierre and Miquelon": "https://i.imgur.com/hA0zOQ9.png",
    "Saint Vincent and the Grenadines": "https://i.imgur.com/5gvGMF7.png",
    "Saint Barthelemy": "https://i.imgur.com/SxXpZ3k.png",
    "Samoa": "https://i.imgur.com/vYMeAyD.png",
    "San Marino": "https://i.imgur.com/2ap0Wmg.png",
    "Sao Tome and Principe": "https://i.imgur.com/dJ8itdu.png",
    "Saudi Arabia": "https://i.imgur.com/P9PwNCj.png",
    "Scotland": "https://i.imgur.com/tf5ImGG.png",
    "Senegal": "https://i.imgur.com/ZPgiu4W.png",
    "Serbia": "https://i.imgur.com/ZbRq53G.png",
    "Seychelles": "https://i.imgur.com/SnvCCkU.png",
    "Sierra Leone": "https://i.imgur.com/dOwQeZ7.png",
    "Singapore": "https://i.imgur.com/KGAyAOH.png",
    "Slovakia": "https://i.imgur.com/8n6obqz.png",
    "Slovenia": "https://i.imgur.com/L9cZ1It.png",
    "SMOM": "https://i.imgur.com/9jCxPF3.png",
    "Solomon Islands": "https://i.imgur.com/BYLzkcb.png",
    "Somalia": "https://i.imgur.com/cLAsJnn.png",
    "South Africa": "https://i.imgur.com/q1zKWUi.png",
    "South Georgia": "https://i.imgur.com/IBm4HT7.png",
    "Spain": "https://i.imgur.com/heAtpVl.png",
    "SPM": "https://i.imgur.com/0xlw4sO.png",
    "Sri Lanka": "https://i.imgur.com/Kz6Po9C.png",
    "Sudan": "https://i.imgur.com/nPueBHt.png",
    "Suriname": "https://i.imgur.com/SBNCcFz.png",
    "Svalbard": "https://i.imgur.com/cKuYoOf.png",
    "SVG": "https://i.imgur.com/hCMI5mW.png",
    "Swaziland": "https://i.imgur.com/SgHU3Vu.png",
    "Sweden": "https://i.imgur.com/Mho3pjS.png",
    "Switzerland": "https://i.imgur.com/snkdzhM.png",
    "Syria": "https://i.imgur.com/d3Fs0ki.png",
    "Taiwan": "https://i.imgur.com/L4eDadU.png",
    "Tajikistan": "https://i.imgur.com/RTjsmX8.png",
    "Tanzania": "https://i.imgur.com/UNHWNVR.png",
    "Thailand": "https://i.imgur.com/fll4Lib.png",
    "Timor Leste": "https://i.imgur.com/stbK2qf.png",
    "Togo": "https://i.imgur.com/ShmhRFK.png",
    "Tokelau": "https://i.imgur.com/X0Zd1QL.png",
    "Tonga": "https://i.imgur.com/V13bRwg.png",
    "Trinidad and Tobago": "https://i.imgur.com/VuMjl4w.png",
    "Tunisia": "https://i.imgur.com/tqJuN7Y.png",
    "Turkey": "https://i.imgur.com/Yjh8AYG.png",
    "Turkmenistan": "https://i.imgur.com/dBh7oYb.png",
    "Turks and Caicos Islands": "https://i.imgur.com/Iv8Ip1D.png",
    "Tuvalu": "https://i.imgur.com/NHYmLFU.png",
    "Uganda": "https://i.imgur.com/IIDfqo6.png",
    "Ukraine": "https://i.imgur.com/qsonbSF.png",
    "United Arab Emirates": "https://i.imgur.com/MiIIyjY.png",
    "United Kingdom": "https://i.imgur.com/tBfa1sR.png",
    "United States": "https://i.imgur.com/IntH6e1.png",
    "Uruguay": "https://i.imgur.com/55aqbjp.png",
    "Uzbekistan": "https://i.imgur.com/fjh4z8g.png",
    "Vanuatu": "https://i.imgur.com/K42aHJW.png",
    "Vatican City": "https://i.imgur.com/Us1cTzD.png",
    "Venezuela": "https://i.imgur.com/bk1O4Ws.png",
    "Vietnam": "https://i.imgur.com/l9gHKN2.png",
    "Virgin Islands": "https://i.imgur.com/ghnxFvR.png",
    "Wales": "https://i.imgur.com/knL0fpB.png",
    "Wallis and Futuna": "https://i.imgur.com/oXd7YJC.png",
    "Western Sahara": "https://i.imgur.com/lpIbaxR.png",
    "Yemen": "https://i.imgur.com/ZEL92UX.png",
    "Zambia": "https://i.imgur.com/R3iYLsX.png",
    "Zimbabwe": "https://i.imgur.com/jFuZNO1.png",
}
